# Generated by Django 2.2.8 on 2020-01-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpage',
            old_name='tank_you_text',
            new_name='thank_you_text',
        ),
    ]
